//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbfirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<ghe> ghes { get; set; }
        public virtual DbSet<lichchieu> lichchieux { get; set; }
        public virtual DbSet<nguoidung> nguoidungs { get; set; }
        public virtual DbSet<phim> phims { get; set; }
        public virtual DbSet<phongchieu> phongchieux { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<theloai> theloais { get; set; }
    }
}
