//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nhom
{
    using System;
    using System.Collections.Generic;
    
    public partial class ghe
    {
        public int ma_ghe { get; set; }
        public int ma_phong { get; set; }
        public string ten_ghe { get; set; }
        public string loai_ghe { get; set; }
        public string trang_thai { get; set; }
    
        public virtual phongchieu phongchieu { get; set; }
    }
}
