//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nhom
{
    using System;
    using System.Collections.Generic;
    
    public partial class lichchieu
    {
        public int ma_lich_chieu { get; set; }
        public int ma_phim { get; set; }
        public int ma_phong { get; set; }
        public int nguoi_lap_lich { get; set; }
        public System.DateTime ngay_chieu { get; set; }
        public System.TimeSpan gio_bat_dau { get; set; }
        public decimal gia_ve_co_ban { get; set; }
    
        public virtual phim phim { get; set; }
        public virtual phongchieu phongchieu { get; set; }
        public virtual nguoidung nguoidung { get; set; }
    }
}
