//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nhom
{
    using System;
    using System.Collections.Generic;
    
    public partial class phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phim()
        {
            this.lichchieux = new HashSet<lichchieu>();
        }
    
        public int ma_phim { get; set; }
        public string ten_phim { get; set; }
        public int ma_the_loai { get; set; }
        public int thoi_luong { get; set; }
        public System.DateTime ngay_khoi_chieu { get; set; }
        public Nullable<System.DateTime> ngay_ket_thuc { get; set; }
        public string mo_ta { get; set; }
        public string trang_thai { get; set; }
        public Nullable<int> nguoi_nhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lichchieu> lichchieux { get; set; }
        public virtual nguoidung nguoidung { get; set; }
        public virtual theloai theloai { get; set; }
    }
}
