//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nhom
{
    using System;
    using System.Collections.Generic;
    
    public partial class phongchieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phongchieu()
        {
            this.ghes = new HashSet<ghe>();
            this.lichchieux = new HashSet<lichchieu>();
        }
    
        public int ma_phong { get; set; }
        public string ten_phong { get; set; }
        public string tinh_trang { get; set; }
        public Nullable<int> nguoi_quan_ly { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ghe> ghes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lichchieu> lichchieux { get; set; }
        public virtual nguoidung nguoidung { get; set; }
    }
}
