//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nhom
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        public int ma_san_pham { get; set; }
        public string ten_san_pham { get; set; }
        public string loai { get; set; }
        public decimal gia_ban { get; set; }
        public int so_luong_ton { get; set; }
        public string trang_thai { get; set; }
        public Nullable<int> nguoi_cap_nhat { get; set; }
    
        public virtual nguoidung nguoidung { get; set; }
    }
}
